import type { Metadata } from 'next'
import { Encode_Sans } from 'next/font/google'
import './globals.css'

const displayFont = Encode_Sans({ weight: '800', subsets: ['latin-ext'], variable: '--font-display' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${displayFont.variable}`}>{children}</body>
    </html>
  )
}
